server:
  port: 1710
  servlet:
    context-path: /zuul

eureka:
  instance:
    prefer-ip-address: true #使用ip注册
    instance-id: zuul-0-hystrix  #服务熔断
  client:
    service-url:
      defaultZone: http://xia:123@springcloud.eureka0:1310/eureka/eureka/,http://xia:123@springcloud.eureka1:1311/eureka/eureka/,http://xia:123@springcloud.eureka2:1312/eureka/eureka/

zuul:
  routes:
    myprovider.serviceId: springcloud-provider  #zuul映射
    myprovider.path: /provider-ss/**
    myconsumer.serviceId: springcloud-consumer0
    myconsumer.path: /consumer-ss-0/**
  #ignored-services: springcloud-provider,springcloud-consumer0 #忽略真实名称 ,"*" 忽略所有的;
  ignored-services: "*"
  prefix: /ciel  #前缀


spring:
  application:
    name: springcloud-zuul
  security:
    user:
      name: xia
      password: 123

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB
  resources:
    static-locations: classpath:/static/ #配置静态资源路径,隔开多个
  thymeleaf:
    prefix: classpath:/templates/  #模板路径
    suffix: .html
    mode: html5
    encoding: utf-8
    servlet:
      content-type: text/html
  profiles:
    active: dev #激活dev模式
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.ciel.cl:1601/ssh-data?seUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: ciel
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
    show-sql: true
    database: mysql
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  rabbitmq:
    host: 127.0.0.1 #rabbitMQ
    port: 5672
    username: ciel
    password: c
    virtual-host: /
  redis:
    host: redis.ciel.cl
    port: 6379
  mail:
    username: 15966504931@163.com #邮箱账户
    password: xiapeixin7 #授权码
    host: smtp.163.com
  aop:
    proxy-target-class: true #使用cglib代理
  cloud:
    config:
      name: springcloud-provider
      server:
        git:
          uri: https://github.com/cielswift/spring-cloud-config.git #远程配置,也可以写其他服务的地址,比如http://127.0.0.1:1310/eureka/,通过springcloudconfig获取其他服务的地址
      profile:
      label: master
---
spring:
  profiles: dev #dev模式
logging:
  config: classpath:logback-spring.xml

fileUpload:
  img:
    user: C:/CustomSoftware/Nginx-Cluster/nginx-1.16.1/static/img/user/
fileRequest:
  img:
    user: http://nginx.ciel.cl/img/user/

